services:

  app:
    build: .
    container_name: juicios-app
    ports:
      - "8080:80"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: juicio_evaluativo
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: juicios-postgres
    environment:
      POSTGRES_DB: juicio_evaluativo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: